"""empty message

Revision ID: 51be8a66f9c9
Revises: 738ed51d7469
Create Date: 2020-03-15 21:46:40.069860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51be8a66f9c9'
down_revision = '738ed51d7469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'start_time')
    # ### end Alembic commands ###
